// Copyright 2022 Stichting ThingsIX Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package frequency_plan

import "github.com/biter777/countries"

var CountryToPlan = map[countries.CountryCode]string{
	countries.AlandIslands:              "EU868",
	countries.Albania:                   "EU868",
	countries.Andorra:                   "EU868",
	countries.Armenia:                   "EU868",
	countries.Austria:                   "EU868",
	countries.Bahrain:                   "EU868",
	countries.Belarus:                   "EU868",
	countries.Belgium:                   "EU868",
	countries.Benin:                     "EU868",
	countries.Bhutan:                    "EU868",
	countries.Bonaire:                   "EU868",
	countries.BosniaAndHerzegovina:      "EU868",
	countries.Botswana:                  "EU868",
	countries.Bouvet:                    "EU868",
	countries.Bulgaria:                  "EU868",
	countries.Burundi:                   "EU868",
	countries.CaboVerde:                 "EU868",
	countries.Comoros:                   "EU868",
	countries.Croatia:                   "EU868",
	countries.Cyprus:                    "EU868",
	countries.CzechRepublic:             "EU868",
	countries.Denmark:                   "EU868",
	countries.Egypt:                     "EU868",
	countries.EquatorialGuinea:          "EU868",
	countries.Estonia:                   "EU868",
	countries.FalklandIslands:           "EU868",
	countries.FaroeIslands:              "EU868",
	countries.Finland:                   "EU868",
	countries.France:                    "EU868",
	countries.FrenchGuiana:              "EU868",
	countries.FrenchPolynesia:           "EU868",
	countries.FrenchSouthernTerritories: "EU868",
	countries.Georgia:                   "EU868",
	countries.Germany:                   "EU868",
	countries.Gibraltar:                 "EU868",
	countries.Greece:                    "EU868",
	countries.Greenland:                 "EU868",
	countries.Guadeloupe:                "EU868",
	countries.Guernsey:                  "EU868",
	countries.HolySee:                   "EU868",
	countries.Hungary:                   "EU868",
	countries.Iceland:                   "EU868",
	countries.Iran:                      "EU868",
	countries.Ireland:                   "EU868",
	countries.IsleOfMan:                 "EU868",
	countries.Italy:                     "EU868",
	countries.Jersey:                    "EU868",
	countries.Kenya:                     "EU868",
	countries.Kuwait:                    "EU868",
	countries.Kosovo:                    "EU868",
	countries.Laos:                      "EU868",
	countries.Latvia:                    "EU868",
	countries.Lebanon:                   "EU868",
	countries.Liechtenstein:             "EU868",
	countries.Lithuania:                 "EU868",
	countries.Luxembourg:                "EU868",
	countries.Macedonia:                 "EU868",
	countries.Madagascar:                "EU868",
	countries.Malta:                     "EU868",
	countries.Martinique:                "EU868",
	countries.Mauritania:                "EU868",
	countries.Mayotte:                   "EU868",
	countries.Moldova:                   "EU868",
	countries.Monaco:                    "EU868",
	countries.Montenegro:                "EU868",
	countries.Namibia:                   "EU868",
	countries.Netherlands:               "EU868",
	countries.NewCaledonia:              "EU868",
	countries.Nigeria:                   "EU868",
	countries.Norway:                    "EU868",
	countries.Philippines:               "EU868",
	countries.Poland:                    "EU868",
	countries.Portugal:                  "EU868",
	countries.Qatar:                     "EU868",
	countries.Reunion:                   "EU868",
	countries.Romania:                   "EU868",
	countries.Rwanda:                    "EU868",
	countries.SaintBarthelemy:           "EU868",
	countries.SaintMartinFrench:         "EU868",
	countries.SaintPierreAndMiquelon:    "EU868",
	countries.Samoa:                     "EU868",
	countries.SanMarino:                 "EU868",
	countries.SaudiArabia:               "EU868",
	countries.Senegal:                   "EU868",
	countries.Serbia:                    "EU868",
	countries.SintMaartenDutch:          "EU868",
	countries.Slovenia:                  "EU868",
	countries.Slovakia:                  "EU868",
	countries.Somalia:                   "EU868",
	countries.SouthAfrica:               "EU868",
	countries.SouthGeorgiaAndTheSouthSandwichIslands: "EU868",
	countries.Spain:                         "EU868",
	countries.SvalbardAndJanMayenIslands:    "EU868",
	countries.Sweden:                        "EU868",
	countries.Switzerland:                   "EU868",
	countries.Syria:                         "EU868",
	countries.Tunisia:                       "EU868",
	countries.Turkey:                        "EU868",
	countries.Ukraine:                       "EU868",
	countries.UnitedArabEmirates:            "EU868",
	countries.UnitedKingdom:                 "EU868",
	countries.WallisandFutunaIslands:        "EU868",
	countries.Zambia:                        "EU868",
	countries.Australia:                     "AU915",
	countries.NewZealand:                    "AU915",
	countries.Tokelau:                       "AU915",
	countries.PapuaNewGuinea:                "AU915",
	countries.NorfolkIsland:                 "AU915",
	countries.Niue:                          "AU915",
	countries.HeardIslandandMcDonaldIslands: "AU915",
	countries.CookIslands:                   "AU915",
	countries.ChristmasIsland:               "AU915",
	countries.CocosIslands:                  "AU915",
	countries.TimorLeste:                    "AU915",
	countries.Tonga:                         "AU915",
	countries.Argentina:                     "AU915",
	countries.Brazil:                        "AU915",
	countries.Chile:                         "AU915",
}
