// Copyright 2022 Stichting ThingsIX Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package frequency_plan

import "github.com/biter777/countries"

var CountryToPlan = map[countries.CountryCode]string{
	countries.AX: "EU868",
	countries.AL: "EU868",
	countries.AD: "EU868",
	countries.AM: "EU868",
	countries.AT: "EU868",
	countries.BH: "EU868",
	countries.BY: "EU868",
	countries.BE: "EU868",
	countries.BJ: "EU868",
	countries.BT: "EU868",
	countries.BQ: "EU868",
	countries.BA: "EU868",
	countries.BW: "EU868",
	countries.BV: "EU868",
	countries.BN: "EU868",
	countries.BG: "EU868",
	countries.BI: "EU868",
	countries.CV: "EU868",
	countries.CK: "EU868",
	countries.KM: "EU868",
	countries.HR: "EU868",
	countries.CY: "EU868",
	countries.CZ: "EU868",
	countries.DK: "EU868",
	countries.EG: "EU868",
	countries.GQ: "EU868",
	countries.EE: "EU868",
	countries.FK: "EU868",
	countries.FO: "EU868",
	countries.FI: "EU868",
	countries.FR: "EU868",
	countries.GF: "EU868",
	countries.PF: "EU868",
	countries.TF: "EU868",
	countries.GE: "EU868",
	countries.DE: "EU868",
	countries.GI: "EU868",
	countries.GR: "EU868",
	countries.GL: "EU868",
	countries.GP: "EU868",
	countries.GG: "EU868",
	countries.VA: "EU868",
	countries.HU: "EU868",
	countries.IS: "EU868",
	countries.IR: "EU868",
	countries.IE: "EU868",
	countries.IM: "EU868",
	countries.IT: "EU868",
	countries.JE: "EU868",
	countries.KE: "EU868",
	countries.KW: "EU868",
	countries.LA: "EU868",
	countries.LV: "EU868",
	countries.LB: "EU868",
	countries.LI: "EU868",
	countries.LT: "EU868",
	countries.LU: "EU868",
	countries.MK: "EU868",
	countries.MG: "EU868",
	countries.MT: "EU868",
	countries.MQ: "EU868",
	countries.MR: "EU868",
	countries.YT: "EU868",
	countries.MD: "EU868",
	countries.MC: "EU868",
	countries.ME: "EU868",
	countries.NA: "EU868",
	countries.NL: "EU868",
	countries.NC: "EU868",
	countries.NG: "EU868",
	countries.NO: "EU868",
	countries.PH: "EU868",
	countries.PL: "EU868",
	countries.PT: "EU868",
	countries.QA: "EU868",
	countries.RE: "EU868",
	countries.RO: "EU868",
	countries.RW: "EU868",
	countries.BL: "EU868",
	countries.MF: "EU868",
	countries.PM: "EU868",
	countries.WS: "EU868",
	countries.SM: "EU868",
	countries.SA: "EU868",
	countries.SN: "EU868",
	countries.RS: "EU868",
	countries.SK: "EU868",
	countries.SI: "EU868",
	countries.SO: "EU868",
	countries.ZA: "EU868",
	countries.GS: "EU868",
	countries.ES: "EU868",
	countries.SJ: "EU868",
	countries.SE: "EU868",
	countries.CH: "EU868",
	countries.SY: "EU868",
	countries.TN: "EU868",
	countries.TR: "EU868",
	countries.UA: "EU868",
	countries.AE: "EU868",
	countries.GB: "EU868",
	countries.WF: "EU868",
	countries.ZM: "EU868",
}
